name: release

# Triggers on every pushed tag
on:
  push:
    tags:
      - "*"

jobs:
  # Build on Linux because it's faster and .NET is cross-platform
  release-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: little-core-labs/get-git-tag@v3.0.1
        id: get_version

      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Build DLL
        run: dotnet build --configuration Release --no-restore

      - name: Prepare mod folder
        run: |
          mkdir mod
          cp TeammateRevive/bin/Release/TeammateRevive.dll mod/
          cp README.md mod/
          cp manifest.json mod/
          cp readme/icon.png mod/

      - name: Package mod as a zip
        uses: vimtor/action-zip@v1
        with:
          files: mod
          dest: mod.zip

      - name: Upload mod package to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mod.zip
          asset_name: TeammateRevive-${{ steps.get_version.outputs.tag }}.zip
          tag: ${{ github.ref }}
          overwrite: true
